AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 instance"

Resources: 
  NewVolume: 
    Type: AWS::EC2::Volume
    Properties: 
      Size: 100
      AvailabilityZone: 
        Fn::ImportValue: !Sub AvailZone

  MountPoint: 
    Type: AWS::EC2::VolumeAttachment
    Properties: 
      InstanceId:
        Fn::ImportValue: !Sub Instance
      VolumeId: 
        !Ref NewVolume
      Device: /dev/sdh
