apiVersion: v1
kind: Service
metadata:

  name: $APP

  labels:
    app: $APP
  annotations:
    #    service.beta.kubernetes.io/azure-load-balancer-resource-group: dev
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-internal: 24.1.1.9/32
spec:

  #  type: NodePort
  type: LoadBalancer
  #  loadBalancerIP: $LOADBALANCER_IP
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http

    - port: 443
      targetPort: 443
      nodePort: 30443
      name: https

  selector:
    app: $APP
