version: '3.3'

services:

    mysql:
        
        image: mysql:5.7
        
        volumes:
          
          - mysql-data:/var/lib/mysql
        
        ports:

          - 3306:3306
          
        restart: always
        
        environment:
        
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE:      test
            MYSQL_USER:          mysql
            MYSQL_PASSWORD:      mysql

volumes:

    mysql-data: