apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-flask-app
  name: flask-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: my-flask-app
  ports:
    - port: 8000
      targetPort: 5500
