apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-flask-app
  name: flask-app-nodeport
spec:
  type: NodePort
  selector:
    app: my-flask-app
  ports:
    - port: 5500
      targetPort: 5500
      nodePort: 30007
